# Generated by Django 4.1.3 on 2022-11-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributeOne', models.CharField(max_length=200)),
                ('attributeTwo', models.CharField(max_length=200)),
                ('attributeThree', models.CharField(max_length=200)),
            ],
        ),
    ]
